eureka:
  client:
    register-with-eureka: false
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: albums-service
          uri: http://localhost:8090
          predicates:
            - Path=/albums/**
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8222
