eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmedmayara789@gmail.com
    password: nazdhxqyiarqgkit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-circular-references: true
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/mail_spring?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /auth
  port: 8081
